### ISSUE TITLE
Use gradle version catalog for libraries

### ISSUE THREAD

**Issue by e13mort** [terrakok/kmp-web-wizard#16]
It would be great to have version catalog feature with all dependencies listed in a single .toml file as an generator's option. 

https://docs.gradle.org/current/userguide/platforms.html

I could contribute if the idea is approved

**Comment by terrakok** [comment]
The idea is good but I prefer to use the settings.gradle.kts for version catalog :)
As you can see in https://github.com/Kotlin/kmm-production-sample/blob/compose-app/settings.gradle.kts

**Comment by terrakok** [comment]
Done
