### ISSUE TITLE
Add Supabase KMP Client

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [terrakok/kmp-web-wizard#17]
Very happy to see this wizard being revived again! Thank you @terrakok 👏 

Request to please add the `Supabase Kotlin Multiplatform Client` as a dependency option in the Wizard:

https://github.com/supabase-community/supabase-kt

It supports a lot of KMP platforms and should be helpful to a ton of users who are looking for a KMP alternative for `Firebase`.

If it makes sense, it can also be added to your `Compose Multiplatform Web Wizard`.

**Comment by terrakok** [comment]
yes, I know and respect the supabase project, but it doesn't support native (macos/linux/win) targets, does it?

**Comment by terrakok** [comment]
I added it here: https://github.com/terrakok/kmp-awesome/tree/master#-service-sdk

**Comment by shubhamsinghmutualmobile** [comment]
> yes, I know and respect the supabase project, but it doesn't support native (macos/linux/win) targets, does it?

You're right. No issues ⭐ thanks for taking a look 👍

We can close this issue if need be :)
