### ISSUE TITLE
Support direct release library on maven central

### ISSUE THREAD

**Issue by swapnil-musale** [terrakok/kmp-web-wizard#20]
I've used this template to create library [KDeviceInfo](https://github.com/swapnil-musale/KDeviceInfo) and for publishing the library on maven central using the ```./gradlew publishAllPublicationsToSonatypeRepository``` command. But with this command library is being created on staging repository and for every release I've to open nexus site and have to close and release process manually.

Also checked other available gradle command under publishing section but couldn't found any command for direct publishing.
So my question is there any option so could automate this library releasing process ?

**Comment by terrakok** [comment]
As I know, there is no way to publish on the maven central in a single command. If you find it, post it here, please

**Comment by swapnil-musale** [comment]
There are two options to automate the release process : 
1. [gradle-maven-publish-plugin](https://github.com/vanniktech/gradle-maven-publish-plugin) using this plugin with one single command we can publish new version of the library on maven central.
Command  : ```./gradlew publishAndReleaseToMavenCentral --no-configuration-cache```

2. [publish-plugin](https://github.com/gradle-nexus/publish-plugin) not much popular but can consider this as well.
