### ISSUE TITLE
Generate Samples for the targeted platforms

### ISSUE THREAD

**Issue by mr3y-the-programmer** [terrakok/kmp-web-wizard#21]
I've used this wizard to create a new kmp library project structure, but I spent some time setting up samples for the platforms I target in the library just to have a small demo. 

It would be great to generate a sample for each platform target that can be run directly from the IDE.

I can help with a PR if this something is welcome to generate samples for: Android, Desktop, and possibly Web(JS & Wasm), but I'm not on mac, and I lack experience with IOS, so, I'm not sure if I can add a sample for it, but this should be trivial to add by someone else.

**Comment by terrakok** [comment]
done
