### ISSUE TITLE
compose-material-3-gallery demo publish to google play.

### ISSUE THREAD

**Issue by Hynsn** [terrakok/kmp-web-wizard#22]
for compose-material-3-gallery, I want publich it to google play. 
What do you think?

**Comment by terrakok** [comment]
First of all, it is a different repo.
https://github.com/terrakok/compose-material-3-gallery

**Comment by Hynsn** [comment]
> First of all, it is a different repo. https://github.com/terrakok/compose-material-3-gallery

yes, this repo have no issue funcation, so I write this and ask for your permission.

**Comment by terrakok** [comment]
I see no reasons why it is useful. there is a web version: https://terrakok.github.io/compose-material-3-gallery/
